### ISSUE TITLE
JSON parse error when using .gz json file in C++

### ISSUE THREAD

**Issue by rgoldouz** [cms-nanoAOD/correctionlib#113]
Dear @nsmith- and @pieterdavid ,

I added the correctionlib to my C++ code as is described here (Thanks to Ansule)
https://cms-nanoaod.github.io/correctionlib/install.html#usage-from-python-and-c

I use libraries from CMSSW_12_1_1. My code is complied but when I call,
  auto cset = CorrectionSet::from_file("/afs/crc.nd.edu/user/r/rgoldouz/BNV/NanoAnalysis/data/POG/EGM/2017_UL/electron.json.gz");  
I see the following error 

terminate called after throwing an instance of 'std::runtime_error'
  what():  JSON parse error: Invalid value. at offset 0
Aborted

When I unzipped the json file it works. 

I also saw this bug report, https://github.com/cms-nanoAOD/correctionlib/pull/104
But I am not sure how should I fix this issue.

Thanks,
Reza

**Comment by nsmith-** [comment]
Hi,
Indeed gzip support direclty inside C++ evaluator was not added until #104 and is not yet in a CMSSW release. What you can do is install the latest version directly from git, following https://cms-nanoaod.github.io/correctionlib/install.html#inside-cmssw but using `python3 -m pip install --user --no-binary=correctionlib git+https://github.com/cms-nanoAOD/correctionlib.git` to get the very latest version.
This reminds me that we should make a new release with this new change, we'll try to get that done and into CMSSW asap

**Comment by akapoorcern** [comment]
@nsmith- Thanks for the prompt response. The JSONs are all gzip files (from all POGs), and the uncompressed files are not even stored now. So this is indeed an urgent need.

**Comment by nsmith-** [comment]
Release 2.1 is now out, and has this feature. We're also working on including in CMSSW https://github.com/cms-sw/cmsdist/issues/7510

**Comment by nsmith-** [comment]
Correctionlib 2.1 should be available in CMSSW_10_6_30 and CMSSW_12_3_0_pre3 when they come out
