### ISSUE TITLE
Unable to call "Correction::evaluate" in ROOT macro

### ISSUE THREAD

**Issue by khaosmos93** [cms-nanoAOD/correctionlib#114]
Dear experts,

I have been trying to use the correctionlib in a ROOT macro within a CMSSW environment.

I first manually added the include directory to the ROOT_INCLUDE_PATH after ```cmsenv```.
When I loaded an example BTV SF json and execute ```evaluate```, I got a lot of error messages.

The following snippet reproduces the issue:
```
$ cmsrel CMSSW_12_3_0_pre1
$ cd CMSSW_12_3_0_pre1/src
$ cmsenv

$ export ROOT_INCLUDE_PATH=$ROOT_INCLUDE_PATH:$(correction config --incdir)
$ root -l
root [0] #include "correction.h"
root [1] using correction::CorrectionSet;
root [2] auto corrSet = CorrectionSet::from_file(input-json)  // from /cvmfs/cms.cern.ch/rsync/cms-nanoAOD/jsonpog-integration/POG/BTV/2017_UL/btagging.json.gz
(std::unique_ptr<correction::CorrectionSet, std::default_delete<correction::CorrectionSet> > &) std::unique_ptr -> 0x7b8c100
root [3] corrSet->validate()
(bool) true
root [4] auto corr = corrSet->at("deepJet_comb")
(std::shared_ptr<const correction::Correction> &) std::shared_ptr -> 0x8fe7100
root [5] corr->evaluate({"central", "M", 5, 1.2, 240.})

In module 'ROOTNTuple':
/data/cmsbld/jenkins/workspace/auto-builds/CMSSW_12_1_0_pre5-slc7_amd64_gcc900/build/CMSSW_12_1_0_pre5-build/slc7_amd64_gcc900/external/gcc/9.3.0/bin/../lib/gcc/x86_64-unknown-linux-gnu/9.3.0/../../../../include/c++/9.3.0/variant:156:13: error: cannot cast private base class 'std::__detail::__variant::_Variant_storage<false, int, double, std::__cxx11::basic_string<char>
      >' to 'std::variant<int, double, std::__cxx11::basic_string<char> >'
            return static_cast<variant<_Types...>&>(__rhs);
... more errors ...
```

Would there be a solution for this?

Thanks,
Minseok

**Comment by pieterdavid** [comment]
The missing line is `gSystem->Load("libcorrectionlib.so")` (with the full path to the shared library); this is not explicitly in the documentation (maybe we need another example), but it's the same thing as done for PyROOT from [here](https://github.com/cms-nanoAOD/correctionlib/blob/master/src/correctionlib/binding.py#L21-L25).
Please note that for reading .json.gz files from C++ you'll need to make sure you have version 2.1 (released two days ago) or a recent local build from the main branch, but from the description I think you're already doing that

**Comment by khaosmos93** [comment]
@pieterdavid Thank you very much. It solves the issue!

**Comment by jaimeleonh** [comment]
Dear experts, 

I'm trying to run correctionlib under RDataFrame, as done in [this example](https://gist.github.com/pieterdavid/a560e65658386d70a1720cb5afe4d3e9#file-df-py). When doing that, I obtained the same error than the one posted here, so I thought reopening this issue would be appropiated. The script I'm running is

```
import ROOT as gbl
import correctionlib
correctionlib.register_pyroot_binding()

f = gbl.TFile.Open("data.root") # file from ggHH->bbtt from 2018
df = gbl.ROOT.RDataFrame(f.Get("Events"))

gbl.gInterpreter.Declare('auto corrSet = correction::CorrectionSet::from_file("btagging.json");') # obtained from /cvmfs/cms.cern.ch/rsync/cms-nanoAOD/jsonpog-integration/POG/BTV/2017_UL/btagging.json.gz
gbl.gInterpreter.Declare('auto corr = corrSet->at("deepJet_comb");')

df = df.Define("number", 'corr->evaluate({"central", "M", 5, 1.2, 240.});')

histo = df.Histo1D("number")
c = ROOT.TCanvas()
histo.Draw()
c.SaveAs("test_plot.pdf")
```

When running in a new CMSSW_12_3_0_pre1 area under python3, the error appears.

Thanks for your help,
Jaime

**Comment by jaimeleonh** [comment]
Hi, sorry to bother, was anybody able to have a look at this? Thanks!

**Comment by swertz** [comment]
It looks similar to #121, could you give a try at the [solution posted there](https://github.com/cms-nanoAOD/correctionlib/issues/121#issuecomment-1033040803)?

**Comment by jaimeleonh** [comment]
Indeed, this solution works. Thanks for your help!
