### ISSUE TITLE
Alternative xxhash implementation

### ISSUE THREAD

**Issue by nsmith-** [cms-nanoAOD/correctionlib#146]
The conda-forge feedstock cannot build v2.2.1 on non-x86 platforms https://github.com/conda-forge/correctionlib-feedstock/pull/8
due to errors like
```
  In file included from /home/conda/feedstock_root/build_artifacts/correctionlib_1663008272199/work/src/correction.cc:10:
  /home/conda/feedstock_root/build_artifacts/correctionlib_1663008272199/work/xxhash/include/xxhash.hpp:45:10: fatal error: immintrin.h: No such file or directory
     45 | #include <immintrin.h>
        |          ^~~~~~~~~~~~~
  compilation terminated.
```
Perhaps https://github.com/Cyan4973/xxHash can be built for all platforms?

**Comment by lgray** [comment]
So - looking at it a bit. A PR to https://github.com/RedSpah/xxhash_cpp could be made to add in the proper compiler guards but it's a bit of a PITB to make sure everything is annotated correctly (and to make sure algorithms are properly done). But you can crib from Cyan4973. Judging from conda https://github.com/Cyan4973/xxHash can be built reasonably easily for all relevant platforms, but then library hell.

**Comment by lgray** [comment]
Looking even more. It seems the compiled parts of the other xxhash are fairly trivial, the `.c` just includes the header and there's no further meat. Shouldn't be that bad!
