### ISSUE TITLE
PyHEP 2022 "proceedings"

### ISSUE THREAD

**Issue by eduardo-rodrigues** [cms-nanoAOD/correctionlib#153]
Hi @nsmith-, can you provide a tag or upload the notebook you used for your presentation at PyHEP 2022 (https://indico.cern.ch/event/1150631/timetable/#20-correctionlib) so that I attach it to the "proceedings" https://zenodo.org/communities/pyhep2022? Advance thanks.

**Comment by nsmith-** [comment]
The notebook for the tutorial is at https://github.com/cms-nanoAOD/correctionlib/blob/b27578648ca3e373175879e8c2e24ebc2bcf29e0/binder/correctionlib_tutorial.ipynb
