### ISSUE TITLE
Optimize bin lookup for uniform binning

### ISSUE THREAD

**Issue by nsmith-** [cms-nanoAOD/correctionlib#177]
In Binning https://github.com/cms-nanoAOD/correctionlib/blob/4a2e7c51de8cd4fbcc65ac71a71de9e85db625b5/src/correction.cc#L348 and in MultiBinning https://github.com/cms-nanoAOD/correctionlib/blob/4a2e7c51de8cd4fbcc65ac71a71de9e85db625b5/src/correction.cc#L427 nodes, currently the bin position is determined by an O(log n) search. For uniform binning, this could be an O(1) operation. We could auto-detect uniform binning in the constructors and switch to a more efficient lookup.

**Comment by eguiraud** [comment]
I'm picking this up as discussed

**Comment by eguiraud** [comment]
https://github.com/cms-nanoAOD/correctionlib/pull/181 is a first attempt at addressing this issue for `Binning` (no `MultiBinning` yet).

**Comment by eguiraud** [comment]
#186 should resolve this issue -- it supersedes #181 , solves the problem slightly differently.

**Comment by eguiraud** [comment]
This can be closed now that #186 is merged.
