### ISSUE TITLE
Evaluating Binning on an int input fails with bad variant access

### ISSUE THREAD

**Issue by nsmith-** [cms-nanoAOD/correctionlib#217]
As reported on cms-talk,
```python
import correctionlib.schemav2 as cs
import rich

NJetweight = cs.Correction(
    name="NJetweight",
    version=1,
    inputs=[cs.Variable(name="nJets", type="int", description="Number of jets")],
    output=cs.Variable(name="weight", type="real", description="Multiplicative event weight"),
    data=cs.Binning(
        nodetype="binning",
        input="nJets",
        edges=[0.5, 1.5, 2.5, 3.5, 4.5, 5.5, 6.5],
        content=[1.1, 1.08, 1.06, 1.04, 1.02, 1.0],
        flow="clamp",
    ),
)

NJetweight.to_evaluator().evaluate(1)
```
returns `RuntimeError: bad_variant_access`. The `Binning` node should either:
- Not allow an input of type `int`, or
- Allow an input of type `int` and explicitly cast it to `double` for the purpose of evaluation

Right now it is failing because neither solution is implemented. I'm not sure at the moment which solution makes more sense. We have some precedent for casting between the two, e.g. in the `Transform` node.

Workarounds:
- Change the input type to `real` and make sure to cast the input appropriately
- Change the Binning to a Category node

**Comment by lgray** [comment]
quack

**Comment by nsmith-** [comment]
🦆 typing it is (cast to double)

**Comment by ikrommyd** [comment]
My brain tells me that ints should be cast to floats. Unless that may cause a problem in some correction evaluation, I don’t see why not.
