### ISSUE TITLE
The exported CMake configuration doesn't look for dependencies correctly

### ISSUE THREAD

**Issue by lmoureaux** [cms-nanoAOD/correctionlib#235]
The following `CMakeLists.txt` fails to generate in LCG 104 (correctionlib 2.2.2, but as far as I can tell the code hasn't changed since), with a trivial `test.cc`:
```cmake
cmake_minimum_required(VERSION 3.16 FATAL_ERROR)
project(test)
find_package(correctionlib)
add_executable(test test.cc)
target_link_libraries(test correctionlib)
```
I get the following output:
```
$ cmake -B build $(correction config --cmake)
-- The C compiler identification is GNU 12.1.0
-- The CXX compiler identification is GNU 12.1.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /cvmfs/sft.cern.ch/lcg/releases/gcc/12.1.0-57c96/x86_64-centos7/bin/gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /cvmfs/sft.cern.ch/lcg/releases/gcc/12.1.0-57c96/x86_64-centos7/bin/g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done (0.8s)
CMake Error at /cvmfs/sft.cern.ch/lcg/views/LCG_104/x86_64-centos7-gcc12-opt/cmake/correctionlib-targets.cmake:59 (set_target_properties):
  The link interface of target "correctionlib" contains:

    ZLIB::ZLIB

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

Call Stack (most recent call first):
  /cvmfs/sft.cern.ch/lcg/views/LCG_104/x86_64-centos7-gcc12-opt/cmake/correctionlibConfig.cmake:10 (include)
  CMakeLists.txt:3 (find_package)


-- Generating done (0.0s)
CMake Generate step failed.  Build files cannot be regenerated correctly.
```
The reason is that ZLIB (and Threads) are added as `PUBLIC` dependencies here (not specifying anything equates to `PUBLIC`): https://github.com/cms-nanoAOD/correctionlib/blob/5b75bf5c42e24aea38b994e385e61e8735a08a93/CMakeLists.txt#L52-L55

This informs CMake that any dependent target needs to add link `libz` and `libpthread` explicitly. This is wrong: neither `zlib.h` nor threads are part of the public interface of correctionlib. These should be made `PRIVATE` instead:
```cmake

if(ZLIB_FOUND)
  target_link_libraries(correctionlib PRIVATE ZLIB::ZLIB)
endif()
if(Threads_FOUND AND CMAKE_SYSTEM_NAME STREQUAL "Linux")
  target_link_libraries(correctionlib PRIVATE Threads::Threads)
endif()
```
Note that linking the dependent targets against `libz.so` or `libpthreads.so` is not needed, the linker is smart enough to figure out this part.

Alternatively, [Config.cmake.in](https://github.com/cms-nanoAOD/correctionlib/blob/master/Config.cmake.in) should use [find_dependency](https://cmake.org/cmake/help/latest/module/CMakeFindDependencyMacro.html#command:find_dependency) to find zlib and pthreads at import time.

**Comment by nsmith-** [comment]
Thank you for your report. Would you be interested in making a PR to fix the issue?
If not, I am happy to but may request a review from you if that is ok.

**Comment by lmoureaux** [comment]
Hi @nsmith-, thanks! I'm a bit overwhelmed by the number of PRs I have currently, so it would be great if you could do it. I'm happy to review the PR
