### ISSUE TITLE
correction --version

### ISSUE THREAD

**Issue by lmoureaux** [cms-nanoAOD/correctionlib#236]
I wish it were possible to find out the version of correctionlib by doing:
```
correction --version
```

Currently the most straightforward way seems to be:
```
python -c 'import correctionlib as cl; print(cl.__version__)'
```
This is a bit convoluted.

**Comment by nsmith-** [comment]
You can use `correction config --version` though admittedly it is hard to discover from the help.

**Comment by nsmith-** [comment]
I was going to add `correction -v` but it conflicts with `correction validate -v` which is used to validate against a particular schema version. So I think the best solution is to recommend `correction config --version`. I've made the help slightly more clear by automatically printing subcommand usage in #259
