### ISSUE TITLE
json format for corrections

### ISSUE THREAD

**Issue by azekhan72** [cms-nanoAOD/correctionlib#251]
hello,
i have some corrections which are parametrized bt eta anf pt bins i.e.
```
pt-bins 25-45    eta<1.2      0.9992±0.0288         eta>1.2      0.6476±0.0187

pt-bins 45-60     eta<1.2       0.629±0.0417         eta>1.2       0.7316±0.0678

pt-bins 60-infi     eta<1.2     0.6698±0.0608        eta>1.2     0.9944±0.129
```

i can use correctionlib for other corrections and sf taking help from https://gitlab.cern.ch/cms-nanoAOD/jsonpog-integration/-/tree/master/examples?ref_type=heads

but im not getting how to create a json file for above corrections, is there any specific script which help to create the json file?

Thanks

**Comment by nsmith-** [comment]
You will have to write a script to convert such cases.
Perhaps the [tutorial](https://cms-nanoaod.github.io/correctionlib/correctionlib_tutorial.html) will provide some guidance?

**Comment by nsmith-** [comment]
Was this helpful in the end? If so, I will close the issue

**Comment by azekhan72** [comment]
yes it was helpfull, sorry for delay
