### ISSUE TITLE
Factorized corrections (e.g. for JEC)

### ISSUE THREAD

**Issue by kirschen** [cms-nanoAOD/correctionlib#42]
Maybe I missed the functionality and it already exists, but in order to fully reproduce the JEC-functionality with the evaluator it would be good to be able to chain together various corrections.
The "standard" JEC flow goes like this:
pt' = L1Correction(ptraw, ...)*ptraw
pt'' = L2Relative (pt',...)*pt'
pt''' = L3Absolute (pt'',...)*pt''
pt''' = L2L3Residual (pt''',...)*pt'''

**Comment by nsmith-** [comment]
Nothing exists in the schema or evaluator yet, though it certainly seems reasonable to include a "correction stack" of some sort. I discussed before that manipulating high-level objects (like LorentzVectors) are out of scope, but here it is still just scalars.
We could add a function to the `CorrectionSet` evaluator class to create a `Stack` of named corrections, with a signature that would be the union of each correction's inputs. Perhaps in addition, the CorrectionSet schema could include a new attribute `stacks: List[Stack]` where the Stack is just a list of `Correction` object names that can be found in the `CorrectionSet`. The tricky part is encoding that one of the inputs to subsequent items in the stack is the output of previous items. We could key on the output name, e.g. by setting L1Correction output to `{"name": "pt_L1", "type": "real"}` and the L2Relative input to `{"name": "pt_L1", "type": "real"}` the evaluator would know to feed the output of the first item to the input of the second rather than the input to L1Correction `{"name": "pt_raw", "type": "real"}`.

**Comment by nsmith-** [comment]
One other challenge here is that you want to return a scale factor, but then use a scale-factor-modified input value in subsequent items. I guess this is another case where #3 could be used.

**Comment by lgray** [comment]
This pattern can appear elsewhere with different operands.
I'd suggest a "cumulative correction" class where you specify what to accumulate and how.

instantiation would look something like:
```corr = CumulativeCorrection(sorted_list_of_jecs.cbegin(), sorted_list_of_jets.cend(),  std::multiplies, stacked=true);```

then writing the correction is something like:
```
double corr = 1;
for(auto itr = start; itr != stop; ++itr) {
  corr = operand(itr->evaluate( stacked ? corr*val : val ), corr);
}
```

This way the metadata of how the JECs are applied and in what ordered is factored out and we expose the primitive correction type quite well, and it can be used for other things that show up.

**Comment by nsmith-** [comment]
I guess this interface assumes the first argument is the one to be multiplied? I think in principle the `Stack` object could have some extra attributes saying which inputs need to be rewritten before subsequent `Correction` evaluations.

**Comment by lgray** [comment]
Yeah - could change out `stacked=true` with a passed-in behavior / manipulator of input data, which would be separate from how you accumulate the correction.

**Comment by nsmith-** [comment]
Hi @kirschen have you found time to work on JEC with the latest schema? Is the [generic formula](https://cms-nanoaod.github.io/correctionlib/schemav2.html#correction) feature with something like `min(max(x, [0]), [1])` working well enough in place of the explicit clamping of inputs? For creating the stack of corrections, it would be good to come to some conclusion before shipping the final v2 schema, so if you have any comments on the ideas above it would be helpful.

**Comment by kirschen** [comment]
Hi @nsmith- 
I didn't try out the generic formula, yet, but it looks like directly applicable to the JECs. I did have the clamping with min(max(x, [0]), [1]) in the last iteration, already, and that looks good enough to me:
https://github.com/cms-jet/JECDatabase/blob/master/scripts/JEC2JSON/JEC2JSON.py#L42 
For the stacking what @lgray and you discussed sounds fine to me, standard use case will be to get the accumulated correction factor after the full stack in pretty much all [non-development] cases, so that should be as accessible as possible.
I should be getting more available to get back to this next week.

**Comment by lgray** [comment]
Just gotta watch out for the JECs with `TMath::` namespace in them. :-)

Neat - once this is in I'll probably move coffea to using correctionlib, add in some cross checks in tests.

**Comment by nsmith-** [comment]
Here's my current thought:
```python
class Cumulative(Model):
    """A cumulative correction

    This references other Correction objects in a CorrectionSet and can
    provide a canned recipe for serial application of dependent corrections.
    For example, given corrections corr1(x, y) and corr2(x', z), where
    x' = corr1(x, y) * x, the cumulative correction
    corr(x, y, z) = corr2(x * corr1(x, y), z)
    can be expressed in reference to its component corrections.
    """

    name: str
    description: Optional[str] = Field(
        description="Detailed description of the correction stack"
    )
    variable: str = Field(
        description="Name of the common input variable to update on accumulation"
    )
    op: Literal["*", "+"] = Field(
        description="How to accumulate changes in the input variable"
    )
    stack: List[str] = Field(description="Names of the component corrections")
```
I think it meets the requirements, but I'm not sure how general it is. After some thinking, I realized also that if we added a `Product` node that multiplied its children (standard content type) together, then it could be used in combination with `Transform` nodes to effect the same behavior:
```json
{
  "nodetype": "transform",
  "input": "pt",
  "rule": {
    "nodetype": "product",
    "content": [{...}, {"nodetype": "formula", "expression": "x", "variables": ["pt"]}]
  },
  "content": {...}
  }
}
```
where the dots would hold the normal correction trees (L1Absolute, L2Relative, etc.) I think the downside is that then some correction sets would have many duplicate components. It's also a bit opaque.

**Comment by lgray** [comment]
I think product or node rules would be fine. Wouldn't it fix the nastier problem you mention you could reference the correction trees from the `{...}` in the sum/product or is that too much of a schema change? 

It would still be nice to have `Cumulative` as the user face representation, it makes the most sense from that perspective.
