### ISSUE TITLE
schemav2: CategoryItem key strings automatically converted to integers

### ISSUE THREAD

**Issue by akapoorcern** [cms-nanoAOD/correctionlib#58]
#### If one of the string-based keys of a CategoryItem is purely a number inside quotes, correctionlib converts that key to an integer when saving the JSON.

Example:
In
```
schema.CategoryItem.parse_obj({"key":"2017", "value": SFyearwise(files=file1)})
```
the key appears as an integer in the JSON `"key":2017` and the evaluator raises an error

The keys with some characters in them (example: `"key":"2016preVFP"`) remain strings. The mix and match of "types" lead to an error when evaluating the JSON:
`RuntimeError: Category got a key not of type int, but its input is int type`

I understand one could just make the key as an integer, to begin with, but sometimes mixed keys are needed, like "2016preVFP".

**Comment by nsmith-** [comment]
Ultimately its due to the pydantic policy of type coercion rather than error: https://pydantic-docs.helpmanual.io/usage/models/#data-conversion
It is possible to override the type coercion behavior by using `StrictInt` and `StrictStr` so I did that in #61.
You should now be able to force the keys to remain strings if needed:
```python
In [1]: from correctionlib.schemav2 import CategoryItem

In [2]: CategoryItem.parse_obj({"key": "2016", "value": 1.})
Out[2]: CategoryItem(key='2016', value=1.0)

In [3]: CategoryItem.parse_obj({"key": 2016, "value": 1.})
Out[3]: CategoryItem(key=2016, value=1.0)
```

**Comment by nsmith-** [comment]
You can update your local installation with `pip install git+https://github.com/cms-nanoAOD/correctionlib.git@master` until it is in a new release
