### ISSUE TITLE
Transformation for integer and strings

### ISSUE THREAD

**Issue by IzaakWN** [cms-nanoAOD/correctionlib#65]
Not sure if this counts as feature request or bug as a follow up on Issue https://github.com/cms-nanoAOD/correctionlib/issues/3: Would it be possible to allow integers (and perhaps strings for completion) as an output of a transformation node?

It works fine for floats, but when mapping integer variables (like the TauPOG's `genmatch` or decay modes), an error occurs during evaluation, because the output is a float. I tried something like this:
```
'data': {
  'nodetype': 'transform',
  'input': "genmatch",
  'rule': {
    'nodetype': 'category',
    'input': "genmatch",
    'content': [
      { 'key': 1, 'value': 1 }, # l -> tau_h, prompt
      { 'key': 3, 'value': 1 }  # l -> tau_h, tau decay
    ]
    'default': 0, # everything else
  },
  'content': {
    'nodetype': 'category', # category:genmatch
    'input': "genmatch",
    'default': 1.0,
    'content': [ { 'key': 1, 'value': ... } ]
  }
}
```
The idea here is that for `genmatch==1` and `3`, I want to arrive at the same SF block, and avoid code duplication or the user of having to "merge" 1 and 3. In the above example of fake rate SFs with `genmatch`, this is not too much of an issue as the file is small. In the case of our tau trigger SFs, however, we have extremely fine binning leading to large files, and for several decay modes (namely DM10 and 11), the exact same SFs are used.

In case of strings, there is no immediate use case I can think of, unless someones wants to merge certain systematics of flags, but if it is easy to extend for both integer and strings, which are valid data types for input variables, why not? :p

**Comment by nsmith-** [comment]
Integer transforms should work, I even had some tests for them in https://github.com/cms-nanoAOD/correctionlib/blob/904f69a53646c4cfc99cfdfb61a45e352c7d1998/tests/test_core.py#L887-L901

Can you paste the evaluator error here?

**Comment by IzaakWN** [comment]
Okay, it works for me now. I tested it only two week ago and the evaluator complained about the output not being a float. Maybe I had an older version back then...

**Comment by IzaakWN** [comment]
I did notice that the integer in `value` is converted to a float in the JSON output file, but the evaluator works as expected:
```
'data': { # transform:dm -> category:dm -> float:SF
  'nodetype': 'transform',
  'input': "dm",
  'rule': {
    'nodetype': 'category',
    'input': "dm",
    'default': -1,
    'content': [
      { 'key':  0, 'value':  0 },
      { 'key':  1, 'value':  1 },
      { 'key': 10, 'value': 10 },
      { 'key': 11, 'value': 10 }, # map 11 -> 10
    ]
  },
  'content': {
    'nodetype': 'category',
    'input': "dm",
    'content': [
      { 'key': -1, 'value': -1.00 },
      { 'key':  0, 'value':  1.00 },
      { 'key':  1, 'value':  1.01 },
      { 'key': 10, 'value':  1.10 },
      { 'key': 11, 'value':  1.11 },
    ]
  }
}
```
in python yields
```
"data": {
  "nodetype": "transform",
  "input": "dm",
  "rule": {
    "nodetype": "category",
    "input": "dm",
    "content": [
      { "key": 0, "value": 0.0 },
      { "key": 1, "value": 1.0 },
      { "key": 10, "value": 10.0 },
      { "key": 11, "value": 10.0 }
    ],
    "default": -1.0
  },
  "content": {
    "nodetype": "category",
    "input": "dm",
    "content": [
      { "key": -1, "value": -1.0 },
      { "key": 0, "value": 1.0 },
      { "key": 1, "value": 1.01 },
      { "key": 10, "value": 1.1 },
      { "key": 11, "value": 1.11 }
    ]
  }
}
```
