### ISSUE TITLE
Baseline structure for corrections

### ISSUE THREAD

**Issue by afrankenthal** [cms-nanoAOD/correctionlib#75]
As discussed today in the xPOG meeting, here is a summary of the structure for corrections that seems reasonable given the POG and analyzer needs:

- Sub-directory level: different years and eras (e.g. 2016UL, 2017EOY, etc.) --> naming to be standardized by xPOG
- Then one .json file per sub-directory containing one CorrectionSet object
- Each CorrectionSet can have many corrections: e.g. Reco, ID, trigger
- Those corrections can be produced independently and merged together into one CorrectionSet by a generic (i.e. xPOG-level) merging tool
- Different working points will constitute a category inside a given correction (but each correction is independent and can have whatever categories are needed)
- This allows corrections to be separately updated by re-merging the separate corrections into a new CorrectionSet and pushing the new .json file
- (Though xPOG versioning still needs to be figured out)

Example generic structures:

POG/Muon/2017UL/muon.json
  |--- RecoCorrection
  |--- IDCorrection
  ----> |--- Loose
  ----> |--- Medium 
  ----> |--- Tight
  |--- TriggerCorrection

POG/Tau/2016Legacy/tau.json
  |--- DeepTauIDElectronCorrection
  |--- DeepTauIDJetCorrection
  |--- DeepTauIDEMuCorrection
  |--- DeepTauIDJetCorrection
  |--- TriggerCorrection
  |--- TauEnergyScaleCorrection

**Comment by mariadalfonso** [comment]
> As discussed today in the xPOG meeting, here is a summary of the structure for corrections that seems reasonable given the POG and analyzer needs:
> 
> * Sub-directory level: different years and eras (e.g. 2016UL, 2017EOY, etc.) --> naming to be standardized by xPOG

I created those for the UL, let's go ahead and see if we can get a full set of json.
later we populate the Run2 EOY ...

**Comment by nsmith-** [comment]
Might I suggest moving this to https://gitlab.cern.ch/cms-nanoAOD/jsonpog-integration/-/issues just since the exact layout of that repository is more or less orthogonal to the design of this library?

**Comment by afrankenthal** [comment]
Done here: [https://gitlab.cern.ch/cms-nanoAOD/jsonpog-integration/-/issues/5](https://gitlab.cern.ch/cms-nanoAOD/jsonpog-integration/-/issues/5)

**Comment by nsmith-** [comment]
Thanks!
