### ISSUE TITLE
Asymmetrical flow type

### ISSUE THREAD

**Issue by IzaakWN** [cms-nanoAOD/correctionlib#83]
We ran into a situation where we would like to use clamp for the overflow (high pT), but error for underflow (below offline pT cut) to ensure users don't use trigger SFs in the turn on.

Is there a way to do it currently? Otherwise, one immediate solution is to use `flow=error` and then a last pT edge of 10000 GeV, or maybe use `flow=clamp` and then as hack some category with an empty key list (if possible) for the underflow bin [0,cut] to throw an error. One solution is to have some way to directly throw an error, or to have asymmetric/mixed flow types, something like `underclamp` and `overclamp`.

**Comment by nsmith-** [comment]
Any reason not to use a very large number (or in fact even `inf` should work) for the last bin edge? Seems most straightforward.

**Comment by nsmith-** [comment]
```python
>>> import json
>>> json.dumps(float('inf'))
'Infinity'
```
Sadly, though rapidjson [claims to support](https://rapidjson.org/md_doc_features.html#autotoc_md36) such JSON extensions it doesn't seem to work in practice.

**Comment by nsmith-** [comment]
Ah just have to opt-in: #85

**Comment by IzaakWN** [comment]
Great, thanks a lot, this is a good workaround! We'll have a try.

**Comment by nsmith-** [comment]
Does this work well enough? Should we close the issue?

**Comment by IzaakWN** [comment]
Yes, it worked for us! You can close it, if you like.
https://github.com/cms-tau-pog/correctionlib/blob/1a0d7201178e47547420cb9a62829ab5552ced08/scripts/tau_trigger_convert.py#L142
