### ISSUE TITLE
[question] Memory management of corrections and correction sets in C++

### ISSUE THREAD

**Issue by pieterdavid** [cms-nanoAOD/correctionlib#92]
While interfacing with other C++ code I started wondering why `CorrectionSet::from_file` returns a `std::unique_pointer<CorrectionSet>` instead of a `CorrectionSet` (in both cases the caller needs to take ownership), and `CorrectionSet::at` a `Correction::Ref`, which is a `std::shared_ptr<const Correction>` instead of a `const Correction&` (I don't immediately see the sharing that would explain reference-counting, or is the idea to let the `CorrectionSet` go out of scope while keeping the `Correction` around?).
There are probably good reasons that I don't know, I am just curious.

**Comment by nsmith-** [comment]
> let the CorrectionSet go out of scope while keeping the Correction around

That's one reason it's a shared pointer. Also, with the introduction of [CompoundCorrection](https://cms-nanoaod.github.io/correctionlib/schemav2.html#compoundcorrection) it is necessary to use a shared ownership system for individual `Correction` objects. But probably the initial motivating reason is that it makes the pybind11 interface simpler.

> `std::unique_pointer<CorrectionSet>` instead of a CorrectionSet

Earlier on, one of the correction nodes was not copy-constructible, and hence the whole CorrectionSet was not. So this is why it was not returned by value (even though copy-elision optimization would have removed such copies in the end). Now I believe everything is copy-constructible but by then the API was established.

**Comment by pieterdavid** [comment]
OK, thanks for explaining!
